<?php
    require(DIRECTORY_MODELS."/MujLogin.class.php");
    global $login;
    $login = new MujLogin();

?>
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>strankyDisgn</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/Articles-Badges-images.css?h=4f3cfa46e40e236365345fc77963f4b8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="/assets/css/Ludens---1-Index-Table-with-Search--Sort-Filters-v20.css?h=91a6735e58e9649a2c62ca9c4550fa69">
    <link rel="stylesheet" href="/assets/css/Navbar-Right-Links-Dark-icons.css?h=befd8a398792e305b7ffd4a176b5b585">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="assets/js/funkce.js"></script>
</head>

<body>
<nav class="navbar navbar-expand-md bg-secondary py-3" data-bs-theme="dark" style="--bs-success: #329366;--bs-success-rgb: 50,147,102;--bs-primary: #5afd0d;--bs-primary-rgb: 90,253,13;background: var(--bs-light-border-subtle);color: var(--bs-light-text-emphasis);--bs-secondary: #a47c4e;--bs-secondary-rgb: 164,124,78;">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="index.php?page=hlavnistranka"><span>Konferenční systém Parsek</span></a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>


        <div class="collapse navbar-collapse" id="navcol-5">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=hlavnistranka">
                        Hlavní stránka
                    </a>
                </li>
                <?php
                    if ($login->isUserLogged()) {
                        if ($login->getRole() == 3 || $login->getRole() == 4) {

                ?>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=spravauzivatelu">
                        Správa uživatelů
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=spravaclankuadmin">
                        Správa recenzí
                    </a>
                </li>
                <?php
                        } else if ($login->getRole() == 1) {
                            ?>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=nahraniclanku">
                        Nahrání vlastního článku
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=spravaclankupisar">
                        Správa článků
                    </a>
                </li>
                <?php
                        } else if ($login->getRole() == 2) {
                            ?>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=spravaclankurecenzent">
                        Články na zhodnocení
                    </a>
                </li>
                <?php
                        }
                    } else {
                ?>
                <li>
                    <a href="index.php?page=prihlaseni">
                        <button class="btn btn-light text-center" type="button" href="index.php?page=prihlaseni">
                            Přihlásit se
                        </button>
                    </a>
                </li>
                <?php
                    }
                ?>

                <?php
                if ($login->isUserLogged()) {

                    ?>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?page=spravavlastnichudaju">
                            Přihlášen/a: <?= $login->getJmeno() ?>
                        </a>
                    </li>
                <li class="nav-item">
                    <a href="index.php?page=odhlaseni">
                        <button class="btn btn-info" type="button" name="action" value="odhlaseni">
                            Odhlásit se
                        </button>
                    </a>
                </li>
                <?php
                }
                ?>

            </ul>
        </div>
    </div>
</nav>


<?php
    if(isset($_GET["page"]) && array_key_exists($_GET["page"], WEB_PAGES)){
        $pageKey = $_GET["page"]; // nastavim pozadovane
    } else {
        $pageKey = DEFAULT_WEB_PAGE_KEY; // defaulti klic
    }
    // pripravim si data ovladace
    $pageInfo = WEB_PAGES[$pageKey];

    require_once(DIRECTORY_CONTROLLERS ."/". $pageInfo["file_name"]);

    // nactu ovladac a bez ohledu na prislusnou tridu ho typuju na dane rozhrani
    /** @var IController $controller  Ovladac prislusne stranky. */
    $controller = new $pageInfo["class_name"];
    // zavolam prislusny ovladac a vypisu jeho obsah
    echo $controller->show();
?>


<footer class="text-center py-4" style="color: var(--bs-body-bg);">
    <div class="container">
        <div class="row row-cols-1 row-cols-lg-3">
            <div class="col-xl-12" style="color: var(--bs-body-bg);">
                <p class="text-dark-emphasis my-2" style="border-color: var(--bs-body-color);">Stránka Parsek</p>
            </div>
        </div>
    </div>
</footer>
</section>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="/assets/js/Ludens---1-Index-Table-with-Search--Sort-Filters-v20-Ludens---1-Index-Table-with-Search--Sort-Filters.js?h=0b5112c06ff3094624f33df374e70be1"></script>
<script src="/assets/js/Ludens---1-Index-Table-with-Search--Sort-Filters-v20-Ludens---Material-UI-Actions.js?h=06c93bc70611575b0c0ad4e1a835f53c"></script>
<script type="text/javascript" src="assets/js/funkce.js"></script>
<script src="assets/js/funkce.js"></script>
</body>

</html>
